services:
  ticketsoup:
    container_name: ticketsoup
    image: ghcr.io/aiibe/ticketsoup:0.4.1
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - pb_data:/pb_data
    environment:
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}

volumes:
  pb_data:
    driver: local
