services:
  ticketsoup:
    container_name: ticketsoup
    image: ghcr.io/aiibe/ticketsoup:0.6.0
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - pb_data:/pb_data
    environment:
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
      - APP_URL=${APP_URL}
      - APP_NAME=${APP_NAME}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_PORT=${SMTP_PORT}

volumes:
  pb_data:
    driver: local
